# Generated by Django 3.0.3 on 2020-03-06 12:23

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('file_upload_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_profile',
            name='is_being_played',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user_profile',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
