# Generated by Django 3.0.2 on 2020-01-30 04:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('file_upload_app', '0003_post_user_profile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user_profile',
            old_name='display_picture',
            new_name='music_file',
        ),
    ]
