# Generated by Django 3.0.2 on 2020-01-30 05:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('file_upload_app', '0004_auto_20200130_1019'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user_profile',
            old_name='fname',
            new_name='music_name',
        ),
        migrations.RemoveField(
            model_name='user_profile',
            name='email',
        ),
        migrations.RemoveField(
            model_name='user_profile',
            name='lname',
        ),
        migrations.RemoveField(
            model_name='user_profile',
            name='technologies',
        ),
    ]
